#!/bin/bash

if [[ $# -ne 5 ]]; then
  echo "USAGE: firmareduce <mapper> <reducer> <input file> <output file> <completion file>"
  exit 1
fi

MAPPER=$1
REDUCER=$2
INPUT_FILE=$3
OUTPUT_FILE=$4
COMPLETION_FILE=$5

export FLAGS_completion_filename=$COMPLETION_FILE
export FLAGS_mr_inputfile=$INPUT_FILE
export FLAGS_mr_outputfile=$OUTPUT_FILE


echo $FLAGS_completion_filename

# Set completion to 2%, that is we started executing.
echo "0.020" > $COMPLETION_FILE
COMMAND="cat $INPUT_FILE |  $MAPPER | sort -k 1 | $REDUCER > $FLAGS_mr_outputfile"
echo "RUNNING COMMAND: $COMMAND"
cat $INPUT_FILE |  $MAPPER \| sort -k 1 | $REDUCER > $FLAGS_mr_outputfile

rm $OUTPUT_FILE
rm $COMPLETION_FILE