#!/bin/bash

if [[ $# -ne 3 ]]; then
  echo "USAGE: firmareduce <mapper> <reducer> <input file>"
  exit 1
fi

export MAPPER=$1
export REDUCER=$2
export INPUT_FILE=$3

export FLAGS_mr_inputfile=$INPUT_FILE
export FLAGS_tasklib_application=mapreduce

export FLAGS_coordinator_uri=tcp:localhost:8088
export FLAGS_resource_id=db904ff2-688e-4d8e-900e-f363e11fd256
export FLAGS_heartbeat_interval=1


# For local test runs.
if [[ -z "$FLAGS_task_id" ]]; then
  export FLAGS_task_id=lolhaxtask
fi

export FLAGS_completion_filename=/tmp/${FLAGS_task_id}_completion

export FLAGS_output_filename=/tmp/${FLAGS_task_id}_output
export FLAGS_tuples_filename=/tmp/${FLAGS_task_id}_tuples


# Set completion to 2%, that is we started executing.
echo "0.020" > $FLAGS_completion_filename

# TODO NAMED PIPES! Get PIDS, pass to reducer.
LD_PRELOAD=/home/gustafa/firmament/build/engine/task_lib_main.so ldpreloader

rm $FLAGS_output_filename
rm $FLAGS_completion_filename
rm $FLAGS_tuple_filename
